cp 0C.aif ./renamed/1C.aif
cp 0Cs.aif ./renamed/1Cs.aif
cp 0D.aif ./renamed/1D.aif
cp 0Ds.aif ./renamed/1Ds.aif
cp 0E.aif ./renamed/1E.aif
cp 0F.aif ./renamed/1F.aif
cp 0Fs.aif ./renamed/1Fs.aif
cp 0G.aif ./renamed/1G.aif
cp 0Gs.aif ./renamed/1Gs.aif
cp 1A.aif ./renamed/2A.aif
cp 1As.aif ./renamed/2As.aif
cp 1B.aif ./renamed/2B.aif
cp 1C.aif ./renamed/2C.aif
cp 1Cs.aif ./renamed/2Cs.aif
cp 1D.aif ./renamed/2D.aif
cp 1Ds.aif ./renamed/2Ds.aif
cp 1E.aif ./renamed/2E.aif
cp 1F.aif ./renamed/2F.aif
cp 1Fs.aif ./renamed/2Fs.aif
cp 1G.aif ./renamed/2G.aif
cp 1Gs.aif ./renamed/2Gs.aif
cp 2A.aif ./renamed/3A.aif
cp 2As.aif ./renamed/3As.aif
cp 2B.aif ./renamed/3B.aif
cp 2C.aif ./renamed/3C.aif
cp 2Cs.aif ./renamed/3Cs.aif
cp 2D.aif ./renamed/3D.aif
cp 2Ds.aif ./renamed/3Ds.aif
cp 2E.aif ./renamed/3E.aif
cp 2F.aif ./renamed/3F.aif
cp 2Fs.aif ./renamed/3Fs.aif
cp 2G.aif ./renamed/3G.aif
cp 2Gs.aif ./renamed/3Gs.aif
cp 3A.aif ./renamed/4A.aif
cp 3As.aif ./renamed/4As.aif
cp 3B.aif ./renamed/4B.aif
cp 3C.aif ./renamed/4C.aif
cp 3Cs.aif ./renamed/4Cs.aif
cp 3D.aif ./renamed/4D.aif
cp 3Ds.aif ./renamed/4Ds.aif
cp 3E.aif ./renamed/4E.aif
cp 3F.aif ./renamed/4F.aif
cp 3Fs.aif ./renamed/4Fs.aif
cp 3G.aif ./renamed/4G.aif
cp 3Gs.aif ./renamed/4Gs.aif
cp 4A.aif ./renamed/5A.aif
cp 4As.aif ./renamed/5As.aif
cp 4B.aif ./renamed/5B.aif
cp 4C.aif ./renamed/5C.aif
cp 4Cs.aif ./renamed/5Cs.aif
cp 4D.aif ./renamed/5D.aif
cp 4Ds.aif ./renamed/5Ds.aif
cp 4E.aif ./renamed/5E.aif
cp 4F.aif ./renamed/5F.aif
cp 4Fs.aif ./renamed/5Fs.aif
cp 4G.aif ./renamed/5G.aif
cp 4Gs.aif ./renamed/5Gs.aif
cp 5A.aif ./renamed/6A.aif
cp 5As.aif ./renamed/6As.aif
cp 5B.aif ./renamed/6B.aif
cp 5C.aif ./renamed/6C.aif
cp 5Cs.aif ./renamed/6Cs.aif
cp 5D.aif ./renamed/6D.aif
cp 5Ds.aif ./renamed/6Ds.aif
cp 5E.aif ./renamed/6E.aif
cp 5F.aif ./renamed/6F.aif
cp 5Fs.aif ./renamed/6Fs.aif
cp 5G.aif ./renamed/6G.aif
cp 5Gs.aif ./renamed/6Gs.aif
cp 6A.aif ./renamed/7A.aif
cp 6As.aif ./renamed/7As.aif
cp 6B.aif ./renamed/7B.aif
cp 6C.aif ./renamed/7C.aif
cp 6Cs.aif ./renamed/7Cs.aif
cp 6D.aif ./renamed/7D.aif
cp 6Ds.aif ./renamed/7Ds.aif
cp 6E.aif ./renamed/7E.aif
cp 6F.aif ./renamed/7F.aif
cp 6Fs.aif ./renamed/7Fs.aif
cp 6G.aif ./renamed/7G.aif
cp 6Gs.aif ./renamed/7Gs.aif
cp 7A.aif ./renamed/8A.aif
cp 7As.aif ./renamed/8As.aif
cp 7B.aif ./renamed/8B.aif
cp 7C.aif ./renamed/8C.aif
